# Generated by Django 5.2.5 on 2025-08-30 13:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="inscription",
            new_name="signup",
        ),
        migrations.RenameField(
            model_name="signup",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="participant",
            name="birthday",
            field=models.DateField(default=None, verbose_name="date de naissance"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="city",
            field=models.CharField(blank=True, max_length=150, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="participant",
            name="country",
            field=models.CharField(blank=True, max_length=150, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AddField(
            model_name="participant",
            name="first_name",
            field=models.CharField(default="", max_length=150, verbose_name="Prénom"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="last_name",
            field=models.CharField(default="", max_length=150, verbose_name="Nom"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="N° tel",
            ),
        ),
    ]
