# Generated by Django 5.2.5 on 2025-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunion", "0002_rename_inscription_participant_signup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_helping_friday",
            field=models.BooleanField(
                default=False,
                help_text="vendredi 3 octobre après-midi (installation matériel, déchargement courses, etc.)",
                verbose_name="Aide pour le vendredi",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_helping_saturday_evening",
            field=models.BooleanField(
                default=False,
                help_text="samedi 4 octobre en fin de journée (rangement)",
                verbose_name="Aide pour le samedi après-midi",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_helping_saturday_morning",
            field=models.BooleanField(
                default=False,
                help_text="samedi 4 octobre matin (installation matériel, déco, aide pour la convergence à vélo,...)",
                verbose_name="Aide pour le samedi matin",
            ),
        ),
    ]
