# Generated by Django 5.2.5 on 2025-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunion", "0003_participant_is_helping_friday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelledParticipant",
            fields=[],
            options={
                "verbose_name": "Cancelled participant",
                "verbose_name_plural": "Cancelled participants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reunion.participant",),
        ),
        migrations.CreateModel(
            name="UnconfirmedParticipant",
            fields=[],
            options={
                "verbose_name": "Unconfirmed participant",
                "verbose_name_plural": "Unconfirmed participants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reunion.participant",),
        ),
        migrations.CreateModel(
            name="ValidatedParticipant",
            fields=[],
            options={
                "verbose_name": "Validated participant",
                "verbose_name_plural": "Validated participants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reunion.participant",),
        ),
        migrations.AddField(
            model_name="participant",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Commentaires"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_helping_friday",
            field=models.BooleanField(
                default=False,
                help_text="vendredi 3 octobre après-midi (installation matériel, déchargement courses, etc.)",
                verbose_name="Aide pour le vendredi après-midi",
            ),
        ),
    ]
