# Generated by Django 5.2.5 on 2025-09-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunion", "0004_cancelledparticipant_unconfirmedparticipant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="payed_at",
            new_name="payment_confirmation_sent_at",
        ),
        migrations.AddField(
            model_name="signup",
            name="cancelled_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for cancelling the signup.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="signup",
            name="status",
        ),
        migrations.AddField(
            model_name="signup",
            name="status",
            field=models.GeneratedField(
                db_persist=False,
                expression=models.Case(
                    models.When(
                        models.Q(("cancelled_at__isnull", False)),
                        then=models.Value("cancelled"),
                    ),
                    models.When(
                        models.Q(
                            ("on_hold__isnull", False),
                            models.Q(("on_hold", ""), _negated=True),
                        ),
                        then=models.Value("on_hold"),
                    ),
                    models.When(
                        models.Q(("validated_at__isnull", True)),
                        then=models.Value("pending"),
                    ),
                    models.When(
                        models.Q(("payment_confirmation_sent_at__isnull", True)),
                        then=models.Value("payment_pending"),
                    ),
                    default=models.Value("validated"),
                ),
                help_text="Status of the signup",
                output_field=models.CharField(max_length=32),
            ),
        ),
    ]
