# Generated by Django 5.2.5 on 2025-09-21 16:03

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reunion",
            "0005_rename_payed_at_signup_payment_confirmation_sent_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signup",
            name="status",
        ),
        migrations.AddField(
            model_name="participant",
            name="amount_due_remaining",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("amount_due_modified"),
                        models.F("amount_due_calculated"),
                    ),
                    "-",
                    models.F("amount_payed"),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
            ),
        ),
    ]
