# Generated by Django 5.2.6 on 2025-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunion", "0006_remove_signup_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signup",
            name="cancelled_reason",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="on_hold",
        ),
        migrations.AddField(
            model_name="signup",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Commentaires"),
        ),
        migrations.AddField(
            model_name="signup",
            name="on_hold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
