# Generated by Django 5.2.6 on 2025-09-21 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reunion",
            "0007_remove_signup_cancelled_reason_remove_signup_on_hold_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="amount_due_remaining",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="amount_payed",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="is_payed",
        ),
    ]
