# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: check-xml
      - id: mixed-line-ending
      - id: check-symlinks
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/rtts/djhtml
    rev: '3.0.11'
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs
