# Generated by Django 3.2.4 on 2021-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballad',
            name='guide',
            field=models.CharField(default='', max_length=220),
            preserve_default=False,
        ),
    ]
