# Generated by Django 3.2.4 on 2021-06-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210627_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(max_length=220, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='adult',
            field=models.BooleanField(default=True, verbose_name='adult'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='firstname',
            field=models.CharField(max_length=56, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lastname',
            field=models.CharField(max_length=56, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.ride', verbose_name='ride'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup', verbose_name='signup'),
        ),
    ]
