# Generated by Django 4.1.7 on 2023-04-18 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# accounts.migrations.0006_alter_signupoperation_options


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_signupoperation"),
        ("accounts", "0003_auto_20221218_2017"),
        ("accounts", "0004_bill_date"),
        ("accounts", "0005_bill_amount"),
        ("accounts", "0006_alter_signupoperation_options"),
        ("accounts", "0007_operationvalidation_validation_type"),
        ("accounts", "0008_alter_operationvalidation_content_type_and_more"),
        ("accounts", "0009_expensereport_signed_expensereport_submitted_date"),
        ("accounts", "0010_expensereport_comments_expensereport_validated_and_more"),
        ("accounts", "0011_delete_justification"),
        ("accounts", "0012_justification"),
        ("accounts", "0013_justification_title"),
        ("accounts", "0014_expensefile"),
        ("accounts", "0015_expensefile_expense_report"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("IBAN", models.CharField(max_length=16, unique=True)),
                (
                    "current_ballance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("number", models.IntegerField()),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("currency", models.TextField(default="EUR")),
                ("effective_date", models.DateField()),
                ("counterparty_IBAN", models.CharField(max_length=255)),
                ("counterparty_name", models.CharField(max_length=255)),
                ("communication", models.CharField(max_length=255)),
                ("reference", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "number")},
            },
        ),
        migrations.CreateModel(
            name="OperationValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.operation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Justification",
            fields=[
                (
                    "operationvalidation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.operationvalidation",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            bases=("accounts.operationvalidation",),
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "date",
                    models.DateField(default=django.utils.datetime_safe.datetime.now),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=11),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignupOperation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
                "verbose_name": "paiement inscriptions 2022",
                "verbose_name_plural": "paiements inscriptions 2022",
            },
            bases=("accounts.operationvalidation",),
        ),
        migrations.AddField(
            model_name="operationvalidation",
            name="validation_type",
            field=models.IntegerField(
                choices=[
                    (
                        "Expenses",
                        [
                            (6010, "matériel"),
                            (6015, "location de matériel"),
                            (6030, "cuisine mobile"),
                            (6031, "encas / collations"),
                            (6041, "marchandises(t-shirts etc)"),
                            (6104, "location salles"),
                            (6111, "frais réunions"),
                            (6120, "fournitures bureau"),
                            (6124, "poste"),
                            (6131, "activités culturelles"),
                            (6132, "photocopies"),
                            (6133, "conférences communiqués presse"),
                            (6135, "brochures"),
                            (6136, "activités sportives"),
                            (6141, "assurance sportive groupe"),
                            (6142, "goodwill - cadeaux"),
                            (6150, "transport organisateurs"),
                            (6151, "indemnités km organisateurs"),
                            (6152, "logement repas organisateurs"),
                            (6153, "voitures suiveuses"),
                            (6154, "transport participants"),
                            (6156, "logement participants"),
                            (6160, "telecom"),
                            (6161, "site web"),
                            (6171, "documentation - cartes"),
                            (6173, "formation"),
                            (6501, "frais bancaires"),
                            (6502, "frais administratifs"),
                        ],
                    ),
                    (
                        "Incomes",
                        [
                            (7000, "INSCRIPTIONS"),
                            (7001, "DONS"),
                            (7002, "SUBSIDES"),
                            (7003, "VENTE MARCHANDISES"),
                            (7512, "PRODUITS BANCAIRES"),
                        ],
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="operationvalidation",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="operationvalidation",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="submitted_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="expensereport",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expensereport",
            name="beneficiary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Justification",
        ),
        migrations.CreateModel(
            name="Justification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                ("title", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "expense_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.expensereport",
                    ),
                ),
            ],
        ),
    ]
