# Generated by Django 3.2 on 2022-12-18 19:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auto_20221218_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
