# Generated by Django 4.1.4 on 2023-02-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0007_operationvalidation_validation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationvalidation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='operationvalidation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
