# Generated by Django 4.1.7 on 2023-02-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_expensereport_comments_expensereport_validated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Justification',
        ),
    ]
