# Generated by Django 4.1.7 on 2023-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_delete_justification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Justification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
