# Generated by Django 4.1.7 on 2023-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
