# Generated by Django 4.1.7 on 2023-03-06 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_expensefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensefile",
            name="expense_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.expensereport",
            ),
        ),
    ]
