# Generated by Django 4.1.7 on 2023-05-29 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_delete_signupoperation_alter_bill_amount_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="operation",
            unique_together={("account", "year", "number")},
        ),
    ]
