# Generated by Django 5.1.5 on 2025-01-26 16:19

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_operation_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"verbose_name": "facture", "verbose_name_plural": "factures"},
        ),
        migrations.AlterModelOptions(
            name="expensefile",
            options={
                "verbose_name": "pièce justificative",
                "verbose_name_plural": "pièces justificatives",
            },
        ),
        migrations.AlterModelOptions(
            name="expensereport",
            options={
                "permissions": [("can_validate", "Can validate expense reports")],
                "verbose_name": "note de frais",
                "verbose_name_plural": "notes de frais",
            },
        ),
        migrations.AddField(
            model_name="expensereport",
            name="iban",
            field=models.CharField(
                default="NO IBAN",
                max_length=34,
                validators=[accounts.models.validate_iban],
                verbose_name="IBAN",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="operationvalidation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=11, verbose_name="montant"
            ),
        ),
        migrations.AlterField(
            model_name="operationvalidation",
            name="validation_type",
            field=models.IntegerField(
                choices=[
                    (
                        "Expenses",
                        [
                            (6010, "matériel"),
                            (6015, "location de matériel"),
                            (6030, "cuisine mobile"),
                            (6031, "encas / collations"),
                            (6041, "marchandises(t-shirts etc)"),
                            (6104, "location salles"),
                            (6111, "frais réunions"),
                            (6120, "fournitures bureau"),
                            (6124, "poste"),
                            (6131, "activités culturelles"),
                            (6132, "photocopies"),
                            (6133, "conférences communiqués presse"),
                            (6135, "brochures"),
                            (6136, "activités sportives"),
                            (6141, "assurance sportive groupe"),
                            (6142, "goodwill - cadeaux"),
                            (6150, "transport organisateurs"),
                            (6151, "indemnités km organisateurs"),
                            (6152, "logement repas organisateurs"),
                            (6153, "voitures suiveuses"),
                            (6154, "transport participants"),
                            (6156, "logement participants"),
                            (6160, "telecom"),
                            (6161, "site web"),
                            (6171, "documentation - cartes"),
                            (6173, "formation"),
                            (6501, "frais bancaires"),
                            (6502, "frais administratifs"),
                        ],
                    ),
                    (
                        "Incomes",
                        [
                            (7000, "INSCRIPTIONS"),
                            (7001, "DONS"),
                            (7002, "SUBSIDES"),
                            (7003, "VENTE MARCHANDISES"),
                            (7512, "PRODUITS BANCAIRES"),
                        ],
                    ),
                ],
                null=True,
                verbose_name="justification",
            ),
        ),
    ]
