# Generated by Django 4.1.7 on 2023-04-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2023)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(default=None, null=True)),
                ("on_hold", models.BooleanField(default=False)),
                ("on_hold_vae", models.BooleanField(default=False)),
                ("on_hold_partial", models.BooleanField(default=False)),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "unique_together": {("owner_id", "year")},
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Nom de Famille"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="adresse e-mail"
                    ),
                ),
                ("phone", models.TextField(blank=True, verbose_name="adresse e-mail")),
                ("birthday", models.DateField(verbose_name="date de naissance")),
                (
                    "city",
                    models.CharField(max_length=150, verbose_name="ville de domicile"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Belgique",
                        max_length=150,
                        verbose_name="pays de résidence",
                    ),
                ),
                (
                    "vae",
                    models.BooleanField(
                        help_text="Vélo à assistance électrique", verbose_name="VAE"
                    ),
                ),
                (
                    "d2022_07_20",
                    models.BooleanField(default=False, verbose_name="20-07"),
                ),
                (
                    "d2022_07_21",
                    models.BooleanField(default=False, verbose_name="21-07"),
                ),
                (
                    "d2022_07_22",
                    models.BooleanField(default=False, verbose_name="22-07"),
                ),
                (
                    "d2022_07_23",
                    models.BooleanField(default=False, verbose_name="23-07"),
                ),
                (
                    "d2022_07_24",
                    models.BooleanField(default=False, verbose_name="24-07"),
                ),
                (
                    "d2022_07_25",
                    models.BooleanField(default=False, verbose_name="25-07"),
                ),
                (
                    "d2022_07_26",
                    models.BooleanField(default=False, verbose_name="26-07"),
                ),
                (
                    "d2022_07_27",
                    models.BooleanField(default=False, verbose_name="27-07"),
                ),
                (
                    "d2022_07_28",
                    models.BooleanField(default=False, verbose_name="28-07"),
                ),
                (
                    "signup_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup2023.signup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payed_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "amount_payed_at",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("calculation", models.TextField(blank=True, default="")),
                (
                    "calculated_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "corrected_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "signup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup2023.signup",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
            },
        ),
    ]
