# Generated by Django 4.1.7 on 2023-04-02 19:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="N° tel",
            ),
        ),
    ]
