# Generated by Django 4.1.7 on 2023-04-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0003_participant_extra_activities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_21",
            new_name="d2023_07_21",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_22",
            new_name="d2023_07_22",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_23",
            new_name="d2023_07_23",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_24",
            new_name="d2023_07_24",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_25",
            new_name="d2023_07_25",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_26",
            new_name="d2023_07_26",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_27",
            new_name="d2023_07_27",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="d2022_07_28",
            new_name="d2023_07_28",
        ),
        migrations.AlterField(
            model_name="participant",
            name="extra_activities",
            field=models.CharField(
                blank=True,
                help_text="Nous cherchons des signaleurs, des capitaines de route. Si vous avez des talents de mécanicien, de secouriste, ousi vous vous proposez pour animer une activité en soirée,merci de nous le faire savoir.",
                max_length=300,
            ),
        ),
    ]
