# Generated by Django 4.1.7 on 2023-05-29 18:06
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0006_alter_participant_vae"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_21",
            field=models.BooleanField(default=True, verbose_name="21-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_22",
            field=models.BooleanField(default=True, verbose_name="22-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_23",
            field=models.BooleanField(default=True, verbose_name="23-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_24",
            field=models.BooleanField(default=True, verbose_name="24-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_25",
            field=models.BooleanField(default=True, verbose_name="25-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_26",
            field=models.BooleanField(default=True, verbose_name="26-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_27",
            field=models.BooleanField(default=True, verbose_name="27-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="d2023_07_28",
            field=models.BooleanField(default=True, verbose_name="28-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="extra_activities",
            field=models.CharField(
                blank=True,
                help_text=("Nous cherchons des signaleurs, des capitaines de route. Si vous avez des talents de "
                           "mécanicien, de secouriste, ou si vous vous proposez pour animer une activité en soirée, "
                           "merci de nous le faire savoir."),
                max_length=300,
                verbose_name="proposition d'aide",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="pre_departure",
            field=models.BooleanField(
                choices=[(False, "Non"), (True, "Oui")],
                default=False,
                help_text=("Je souhaite arriver/loger la veille du départ "
                           "(petit-déjeuner et pique-nique pour le 19 Juillet "
                           "seront prévus pour les personnes inscrites pour la nuit du 18 juillet)."),
                verbose_name="veille",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="vae",
            field=models.BooleanField(
                choices=[(False, "non"), (True, "oui")],
                default=False,
                help_text="Vélo à assistance électrique",
                max_length=17,
                verbose_name="VAE",
            ),
        ),
    ]
