# Generated by Django 5.1.5 on 2025-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0009_alter_participant_day1_alter_participant_day2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="day9",
            field=models.BooleanField(default=True, verbose_name="26-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day1",
            field=models.BooleanField(default=True, verbose_name="18-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day2",
            field=models.BooleanField(default=True, verbose_name="19-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day3",
            field=models.BooleanField(default=True, verbose_name="20-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day4",
            field=models.BooleanField(default=True, verbose_name="21-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day5",
            field=models.BooleanField(default=True, verbose_name="22-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day6",
            field=models.BooleanField(default=True, verbose_name="23-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day7",
            field=models.BooleanField(default=True, verbose_name="24-07"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="day8",
            field=models.BooleanField(default=True, verbose_name="25-07"),
        ),
        migrations.AlterField(
            model_name="signup",
            name="year",
            field=models.IntegerField(default=2025),
        ),
    ]
