# Generated by Django 5.2 on 2025-06-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0010_participant_day9_alter_participant_day1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="corrected_amount",
        ),
        migrations.CreateModel(
            name="ExtraParticipantInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_address",
                    models.CharField(
                        default="",
                        help_text="Nécessaire en cas d'urgence médicale",
                        verbose_name="Addresse complète",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(default="", verbose_name="contact d'urgence"),
                ),
                (
                    "share_contact_info_participants",
                    models.BooleanField(
                        default=False,
                        help_text="Acceptez-vous que nous partagions vos coordonées avec les autres participants?",
                        verbose_name="partage_info",
                    ),
                ),
                (
                    "image_rights",
                    models.BooleanField(
                        default=False,
                        help_text="Acceptez-vous que des photos ou vidéos vous représentant soient diffusées sur les canaux de communication de Dynamobile ?",
                        verbose_name="droit à l'image",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ommentaires éventuels",
                        verbose_name="commentaires",
                    ),
                ),
                (
                    "road_captain",
                    models.BooleanField(
                        default=False,
                        help_text="Je propose mon aide comme capitaine de route (Age minimum 21 ans).",
                        verbose_name="captain de route",
                    ),
                ),
                (
                    "mechanicien",
                    models.BooleanField(
                        default=False,
                        help_text="Je propose mon aide pour réparer les vélos.",
                        verbose_name="méchano",
                    ),
                ),
                (
                    "healthpro",
                    models.BooleanField(
                        default=False,
                        help_text="Je propose mon aide comme secouriste / infirmièr.e / médecin.",
                        verbose_name="infirmièr.e",
                    ),
                ),
                (
                    "animator",
                    models.BooleanField(
                        default=False,
                        help_text="Je propose une animation",
                        verbose_name="animateur",
                    ),
                ),
                (
                    "activite_21",
                    models.TextField(
                        choices=[
                            ("-", "pas d'activité"),
                            (
                                "Wégimont",
                                "Domaine provincial de Wégimont, avec piscine",
                            ),
                            (
                                "Boucle cycliste",
                                "Boucle cycliste plus sportive et militante",
                            ),
                        ],
                        default="-",
                        verbose_name="21/07",
                    ),
                ),
                (
                    "activite_25",
                    models.TextField(
                        choices=[
                            ("-", "pas d'activité"),
                            ("cidrerie", "visite guidée cidrerie 6,5€ p.p."),
                            ("automates", "Boucle cycliste plus sportive et militante"),
                        ],
                        default="-",
                        verbose_name="25/07",
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup2023.participant",
                    ),
                ),
            ],
        ),
    ]
