# Generated by Django 5.2 on 2025-06-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0011_remove_bill_corrected_amount_extraparticipantinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraparticipantinfo",
            name="roadbook",
            field=models.BooleanField(
                default=False,
                help_text="Je souhaite recevoir le carnet de route en version pdf interactive.",
                verbose_name="carnet de route",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="activite_21",
            field=models.TextField(
                choices=[
                    (
                        "absent",
                        "Je suis inscrit.e en partiel. Je ne suis pas là ce jour-là.",
                    ),
                    ("Wégimont", "Domaine provincial de Wégimont, avec piscine"),
                    ("Boucle cycliste", "Boucle cycliste militante (65km)"),
                ],
                default="-",
                verbose_name="Activité choisie le 21/07",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="activite_25",
            field=models.TextField(
                choices=[
                    (
                        "absent",
                        "Je suis inscrit.e en partiel. Je ne suis pas là ce jour-là.",
                    ),
                    ("-", "Pause de midi libre au grand air"),
                    ("cidrerie", "Visite cidrerie (6,5 eur p/p)"),
                    ("automates", "Visite musée des automates (5 eur p/p)"),
                ],
                default="-",
                verbose_name="Activité choisie le 25/07",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="animator",
            field=models.BooleanField(
                default=False,
                help_text="Je propose une animation, précisez ci-dessous.",
                verbose_name="Animations en fin de journée",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                help_text="commentaires éventuels",
                verbose_name="commentaires",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="emergency_contact",
            field=models.CharField(
                default="",
                help_text="Personne à contacter en cas d'urgence (Nom + lien de parenté éventuel + téléphone)",
                verbose_name="Contact en cas d'urgence",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="healthpro",
            field=models.BooleanField(
                default=False,
                help_text="Je propose mon aide comme secouriste / infirmièr·e / médecin.",
                verbose_name="premiers soins",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="image_rights",
            field=models.BooleanField(
                default=False,
                help_text="Acceptez-vous que des photos ou vidéos vous représentant soient diffusées sur les canaux de communication de Dynamobile (site, page Facebook privée)?",
                verbose_name="droit à l'image",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="road_captain",
            field=models.BooleanField(
                default=False,
                help_text="Je propose mon aide comme capitaine de route (Age minimum 21 ans).",
                verbose_name="capitaine de route",
            ),
        ),
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="share_contact_info_participants",
            field=models.BooleanField(
                default=False,
                help_text="Acceptez-vous que nous partagions vos coordonnées avec les autres participant·es?",
                verbose_name="partage de données",
            ),
        ),
    ]
