# Generated by Django 5.2.5 on 2025-08-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0012_extraparticipantinfo_roadbook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="mechanicien",
            field=models.BooleanField(
                default=False,
                help_text="Je propose mon aide pour réparer les vélos.",
                verbose_name="mécano",
            ),
        ),
    ]
