# Generated by Django 6.0.4 on 2026-04-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2023", "0013_alter_extraparticipantinfo_mechanicien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="signup_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_set",
                to="signup2023.signup",
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="year",
            field=models.IntegerField(default=2026),
        ),
    ]
