# Generated by Django 4.0.3 on 2022-04-21 11:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('birthday', models.DateField(verbose_name='date of birth')),
                ('city', models.CharField(max_length=150, verbose_name='city of residence')),
                ('country', models.CharField(default='Belgium', max_length=150, verbose_name='country of residence')),
                ('signup_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup2022.signup')),
            ],
        ),
        migrations.CreateModel(
            name='DaySignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(choices=[(datetime.date(2022, 7, 18), '2022-07-18'), (datetime.date(2022, 7, 19), '2022-07-19'), (datetime.date(2022, 7, 20), '2022-07-20'), (datetime.date(2022, 7, 21), '2022-07-21'), (datetime.date(2022, 7, 22), '2022-07-22'), (datetime.date(2022, 7, 23), '2022-07-23')], validators=[django.core.validators.MinValueValidator(datetime.date(2022, 7, 18)), django.core.validators.MaxValueValidator(datetime.date(2022, 7, 23))])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cancelled', models.DateField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup2022.participant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='daysignup',
            constraint=models.UniqueConstraint(fields=('participant', 'day'), name='no double counting'),
        ),
    ]
