# Generated by Django 4.0.3 on 2022-04-26 17:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('signup2022', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participant',
            managers=[
                ('ojects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_18',
            field=models.BooleanField(default=False, verbose_name='18-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_19',
            field=models.BooleanField(default=False, verbose_name='19-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_20',
            field=models.BooleanField(default=False, verbose_name='20-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_21',
            field=models.BooleanField(default=False, verbose_name='21-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_22',
            field=models.BooleanField(default=False, verbose_name='22-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_23',
            field=models.BooleanField(default=False, verbose_name='23-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_24',
            field=models.BooleanField(default=False, verbose_name='24-07'),
        ),
        migrations.AddField(
            model_name='participant',
            name='d2022_07_25',
            field=models.BooleanField(default=False, verbose_name='25-07'),
        ),
        migrations.DeleteModel(
            name='DaySignup',
        ),
    ]
