# Generated by Django 4.0.3 on 2022-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup2022', '0004_alter_signup_cancelled_at_alter_signup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
