# Generated by Django 4.1.4 on 2022-12-28 21:41

from django.db import migrations, models
from signup2022.models import Bill

def recalculate_amounts(apps, schema_editor):
    for bill in Bill.objects.all():
        total_amount, description = bill.calculate_amount_and_explain()
        bill.calculation = description
        bill.calculated_amount = total_amount
        bill.corrected_amount = bill.amount
        bill.save()


class Migration(migrations.Migration):
    dependencies = [
        ('signup2022', '0006_bill_amount_payed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AddField(
            model_name='bill',
            name='calculation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bill',
            name='corrected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.RunPython(recalculate_amounts, migrations.RunPython.noop)
    ]
