# Generated by Django 6.0.4 on 2026-04-18 06:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="N° tel",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="date de naissance")),
                (
                    "city",
                    models.CharField(max_length=150, verbose_name="ville de domicile"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Belgique",
                        max_length=150,
                        verbose_name="pays de résidence",
                    ),
                ),
                (
                    "vae",
                    models.BooleanField(
                        choices=[(False, "non"), (True, "oui")],
                        default=False,
                        verbose_name="VAE",
                    ),
                ),
                ("day1", models.BooleanField(default=True, verbose_name="17-07")),
                ("day2", models.BooleanField(default=True, verbose_name="18-07")),
                ("day3", models.BooleanField(default=True, verbose_name="19-07")),
                ("day4", models.BooleanField(default=True, verbose_name="20-07")),
                ("day5", models.BooleanField(default=True, verbose_name="21-07")),
                ("day6", models.BooleanField(default=True, verbose_name="22-07")),
                ("day7", models.BooleanField(default=True, verbose_name="23-07")),
                ("day8", models.BooleanField(default=True, verbose_name="24-07")),
                ("day9", models.BooleanField(default=True, verbose_name="25-07")),
                (
                    "amount_due_modified",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_due_calculated",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant 2026",
                "verbose_name_plural": "Participants 2026",
            },
        ),
        migrations.CreateModel(
            name="ExtraParticipantInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Addresse complète",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contact en cas d'urgence",
                    ),
                ),
                (
                    "share_contact_info",
                    models.BooleanField(
                        default=False, verbose_name="Partage de données"
                    ),
                ),
                (
                    "image_rights",
                    models.BooleanField(default=False, verbose_name="Droit à l'image"),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, default="", verbose_name="Commentaires"
                    ),
                ),
                (
                    "road_captain",
                    models.BooleanField(
                        default=False, verbose_name="Capitaine de route"
                    ),
                ),
                (
                    "mechanicien",
                    models.BooleanField(default=False, verbose_name="Mécano"),
                ),
                (
                    "healthpro",
                    models.BooleanField(default=False, verbose_name="Premiers soins"),
                ),
                (
                    "animator",
                    models.BooleanField(default=False, verbose_name="Animations"),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_info",
                        to="signup2026.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2026)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("on_hold", models.BooleanField(default=False)),
                ("on_hold_vae", models.BooleanField(default=False)),
                ("on_hold_partial", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup2026_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription 2026",
                "verbose_name_plural": "Inscriptions 2026",
                "unique_together": {("owner", "year")},
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="signup_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_set",
                to="signup2026.signup",
            ),
        ),
    ]
