# Generated by Django 6.0.4 on 2026-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="arrive_day_before",
            field=models.BooleanField(
                default=False,
                help_text="Le participant arrivera-t-il la veille de l'édition ?",
                verbose_name="Arrivée la veille",
            ),
        ),
    ]
