# Generated by Django 6.0.4 on 2026-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0002_add_arrive_day_before"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signup",
            name="on_hold",
        ),
        migrations.AddField(
            model_name="signup",
            name="on_hold_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
