# Generated by Django 6.0.4 on 2026-04-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0003_on_hold_boolean_to_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Commentaires"),
        ),
    ]
