# Generated by Django 6.0.4 on 2026-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0004_signup_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="extra_activities",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Proposition d'aide",
                max_length=300,
                verbose_name="Proposition d'aide",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="takes_car_back",
            field=models.BooleanField(default=False, verbose_name="Ramène la voiture"),
        ),
    ]
