# Generated by Django 6.0.4 on 2026-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0005_participant_extra_activities_and_more"),
    ]

    operations = [
        # SQLite stores BooleanField as 1/0; convert before AlterField recreates the table
        migrations.RunSQL(
            sql="UPDATE signup2026_participant SET takes_car_back = CASE WHEN takes_car_back = 1 THEN 'brussels' ELSE 'no' END",
            reverse_sql="UPDATE signup2026_participant SET takes_car_back = CASE WHEN takes_car_back = 'brussels' THEN 1 ELSE 0 END",
        ),
        migrations.AlterField(
            model_name="participant",
            name="takes_car_back",
            field=models.CharField(
                choices=[("no", "Non"), ("brussels", "Bruxelles"), ("namur", "Namur")],
                default="no",
                help_text="Le participant rentre-t-il en car depuis Bastogne vers Namur ou Bruxelles ?",
                max_length=10,
                verbose_name="Rentre en car",
            ),
        ),
    ]
