# Generated by Django 6.0.4 on 2026-04-22 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0006_participant_takes_car_back_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListParticipant",
            fields=[],
            options={
                "verbose_name": "Participant en attente 2026",
                "verbose_name_plural": "Participants en attente 2026",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("signup2026.participant",),
        ),
    ]
