# Generated by Django 6.0.4 on 2026-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0008_signup_payment_confirmation_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraparticipantinfo",
            name="july20_loop",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "option1",
                        "Option 1 : réserve naturelle Haff Réimech et parc aquatique Erlefnis Baggerweier",
                    ),
                    (
                        "option2",
                        "Option 2 : boucle sportive via Schengen et la Römer Route",
                    ),
                ],
                default="",
                help_text="Choix de la boucle pour la journée du lundi 20 juillet",
                max_length=10,
                verbose_name="Boucle du 20 juillet",
            ),
        ),
        migrations.AddField(
            model_name="extraparticipantinfo",
            name="tandem_pilot",
            field=models.BooleanField(
                default=False, verbose_name="Accompagner Claude (tandem)"
            ),
        ),
    ]
