# Generated by Django 6.0.6 on 2026-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup2026", "0010_alter_extraparticipantinfo_july20_loop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraparticipantinfo",
            name="full_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Adresse complète"
            ),
        ),
    ]
